version: "2.1"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: streamservice_zookeeper
    ports:
      - "2181:2181"
  kafka:
    restart: always
    image: wurstmeister/kafka:latest
    container_name: streamservice_kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: OUTSIDE://localhost:9092,INSIDE://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "json-stream:1:1"
    ports:
      - "9092:9092"
    expose:
      - 9093
    depends_on:
      - zookeeper
  producer:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: producer_flask_app
    volumes:
      - ./:/stream-kafka
    environment:
      HOST: 127.0.0.1
      PORT: 8001
    ports:
      - "8000:8001"
    depends_on:
      - kafka
      - zookeeper
    entrypoint: 'python3 -u /stream-kafka/producer/manage.py'
